include: "https://gitlab.hami.blue/gitlab-ci.yml"

variables:
  PROJECT_DIR: "sms_gateway"

.project_test:
  extends: .test
  script:
    - source $CI_PROJECT_DIR/venv/bin/activate
    - python manage.py makemigrations
    - coverage run manage.py test
    - coverage html
    - coverage report
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"

  artifacts:
    paths:
      - htmlcov

test_staging:
  extends: .project_test

test_production:
  extends: .project_test
